#!/usr/bin/env python3
"""Regenerate the ability, item and accessory tables.

The tables in internal/kh3/tables.go are derived from the enums in
Xeeynamo/KingdomSaveEditor (GPL-3.0), which is why this project is GPL-3.0.

Run with --check in CI to fail if a committed table no longer matches its
source; run with no flags to regenerate.

The upstream enums carry explicit `= N` anchors that re-base the counter, so a
naive positional parse drifts by several indices. That bug put Soldier's
Earring at 187 instead of 256. The parser below honors them.
"""

import argparse
import os
import re
import subprocess
import sys

UPSTREAM = "https://github.com/Xeeynamo/KingdomSaveEditor.git"
PINNED = "37a7a9dde19463a0d5f0c9588c634d6129e536f6"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFS = os.path.join(ROOT, "refs", "KingdomSaveEditor")
TYPES = os.path.join(REFS, "KHSave.Lib3", "Types")

ENTRY = re.compile(
    r'(?:\[(\w+)\("([^"]*)"\)\]\s*|\[(\w+)\]\s*)?'
    r'([A-Za-z_][A-Za-z0-9_]*)\s*(?:=\s*(\d+))?\s*,'
)


def ensure_upstream():
    if os.path.isdir(TYPES):
        return
    os.makedirs(os.path.dirname(REFS), exist_ok=True)
    print(f"cloning {UPSTREAM} at {PINNED[:12]}", file=sys.stderr)
    subprocess.run(["git", "clone", "--quiet", "--filter=blob:none", UPSTREAM, REFS], check=True)
    subprocess.run(["git", "-C", REFS, "checkout", "--quiet", PINNED], check=True)


def parse_enum(filename, enum_name):
    """Return {index: (category, label)}, honouring `= N` anchors."""
    src = open(os.path.join(TYPES, filename), encoding="utf-8").read()
    body = src[src.index(f"enum {enum_name}"):]
    body = body[body.index("{") + 1:]
    out, idx = {}, 0
    for m in ENTRY.finditer(body):
        cat1, label, cat2, ident, val = m.groups()
        if val is not None:
            idx = int(val)
        out[idx] = (cat1 or cat2 or "", label or ident)
        idx += 1
    return out


def q_py(s):
    return repr(s)


def q_go(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


HEADER = """# kh3-save-editor: offline save tools for Kingdom Hearts III (PC)
# Copyright (C) 2026  thirteenth-order and kh3-save-editor contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See the LICENSE file for the full text.
#
# Portions of the ability and inventory tables in kh3save/abilities.py and
# kh3save/items.py are generated from Xeeynamo/KingdomSaveEditor (GPL-3.0).

"""


def render_abilities(ab):
    L = [HEADER, '"""Ability id -> (category, name) for KH3.\n',
         "Generated by tools/gen_tables.py from KHSave.Lib3/Types/AbilityType.cs",
         "(Xeeynamo/KingdomSaveEditor). The id is the index into the 512-entry",
         'ability array at character + 0x160.\n"""\n', "ABILITIES = {"]
    for i in sorted(ab):
        L.append(f"    0x{i:03X}: ({q_py(ab[i][0])}, {q_py(ab[i][1])}),")
    L.append("}")
    return "\n".join(L) + "\n"


def render_items(items, acc, mapping):
    L = [HEADER, '"""Inventory index -> (category, name) for KH3.\n',
         "Generated by tools/gen_tables.py from KHSave.Lib3/Types/InventoryType.cs",
         "and AccessoryType.cs (Xeeynamo/KingdomSaveEditor).\n",
         "The inventory enum carries explicit `= N` anchors that re-base the",
         "counter, so a naive positional parse drifts; this honors them. Verified",
         "against a real save: the decoded bag reads as Potions, Ethers, AP Boosts,",
         'synthesis shards, food and Gummi blocks.\n"""\n', "ITEMS = {"]
    for i in sorted(items):
        L.append(f"    {i}: ({q_py(items[i][0])}, {q_py(items[i][1])}),")
    L.append("}\n")
    L.append("# Accessory id -> name. A different index space from ITEMS: the equipped")
    L.append("# accessory slots at character + 0xD8 store an AccessoryType id.")
    L.append("ACCESSORIES = {")
    for i in sorted(acc):
        L.append(f"    {i}: {q_py(acc[i][1])},")
    L.append("}\n")
    L.append("# Bridges the two index spaces by name, so we can ask whether an")
    L.append("# inventory item is currently equipped.")
    L.append("ITEM_TO_ACCESSORY = {")
    for i in sorted(mapping):
        L.append(f"    {i}: {mapping[i]},")
    L.append("}")
    return "\n".join(L) + "\n"


def render_go(ab, items, acc, mapping):
    L = ["package kh3", "",
         "// Code generated by tools/gen_tables.py. DO NOT EDIT.",
         "//",
         "// Derived from KHSave.Lib3 (Xeeynamo/KingdomSaveEditor, GPL-3.0), the same",
         "// parse that produces the Python tables, so the two cannot drift.", ""]

    def emit(name, comment, pairs, keyfmt):
        L.append(comment)
        L.append(f"var {name} = map[int]string{{")
        for k, v in pairs:
            L.append(f"\t{keyfmt(k)}: {q_go(v)},")
        L.append("}")
        L.append("")

    emit("Abilities",
         "// Abilities maps an ability id to its display name. The id is the index\n"
         "// into the 512-entry ability array at character + 0x160.",
         [(i, ab[i][1]) for i in sorted(ab)], lambda k: f"0x{k:03X}")
    emit("AbilityCategory", "// AbilityCategory is Action / Support / Mobility / Info.",
         [(i, ab[i][0]) for i in sorted(ab)], lambda k: f"0x{k:03X}")
    emit("Items", "// Items maps an inventory index (the 0x8F4 array) to its name.",
         [(i, items[i][1]) for i in sorted(items)], str)
    emit("ItemCategory", "// ItemCategory is Consumable / Accessory / Synthesis / ...",
         [(i, items[i][0]) for i in sorted(items)], str)
    emit("Accessories",
         "// Accessories maps an AccessoryType id, the number stored in the\n"
         "// equipped-accessory slots at character + 0xD8, a different index space\n"
         "// from Items.",
         [(i, acc[i][1]) for i in sorted(acc)], str)

    L.append("// ItemToAccessory bridges the two index spaces by name, so we can ask")
    L.append("// whether an inventory item is currently equipped.")
    L.append("var ItemToAccessory = map[int]int{")
    for i in sorted(mapping):
        L.append(f"\t{i}: {mapping[i]},")
    L.append("}")
    return "\n".join(L) + "\n"


def gofmt(src):
    """Format generated Go, so the CI gofmt gate and --check agree."""
    try:
        r = subprocess.run(["gofmt"], input=src, capture_output=True, text=True)
    except FileNotFoundError:
        return src  # no Go toolchain here; the CI job that needs it has one
    if r.returncode != 0:
        raise SystemExit("gofmt rejected the generated table:\n" + r.stderr)
    return r.stdout


def build():
    ensure_upstream()
    ab = parse_enum("AbilityType.cs", "AbilityType")
    items = parse_enum("InventoryType.cs", "InventoryType")
    acc = parse_enum("AccessoryType.cs", "AccessoryType")

    by_name = {}
    for aid, (_, name) in acc.items():
        by_name.setdefault(name, aid)
    mapping = {iid: by_name[name] for iid, (cat, name) in items.items()
               if cat == "Accessory" and name in by_name}

    return {
        os.path.join(ROOT, "internal", "kh3", "tables.go"): gofmt(render_go(ab, items, acc, mapping)),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if a committed table differs from its source")
    args = ap.parse_args()

    stale = []
    for path, content in build().items():
        rel = os.path.relpath(path, ROOT)
        if args.check:
            try:
                current = open(path, encoding="utf-8").read()
            except FileNotFoundError:
                stale.append(f"{rel} (missing)")
                continue
            if current != content:
                stale.append(rel)
            else:
                print(f"ok    {rel}")
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            print(f"wrote {rel}")

    if stale:
        print("\nthese generated files are out of date:", file=sys.stderr)
        for s in stale:
            print("  " + s, file=sys.stderr)
        print("\nrun: python tools/gen_tables.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
